# Spark Engine ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: dn-dbt-spark

---
# dbt ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: dbt 
  namespace: dn-dbt

---
# Spark Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: dn-dbt-spark
  name: spark-role 
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["*"]

---
# RoleBinding for Spark ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: spark-rb
  namespace: dn-dbt-spark
subjects:
- kind: ServiceAccount
  name: spark
  namespace: dn-dbt-spark 
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-executor-role
rules: 
  - apiGroups: [""]
    resources: ["pods", "pod/log", "services", "configmaps", "secrets"]
    verbs: ["create", "get", "list", "watch", "delete"]
  
---

# Allow dbt to discover Spark Service
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  namespace: dn-dbt-spark
  name: dbt-discover
rules: 
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: dbt-discover-rb
  namespace: dn-dbt-spark
subjects:
- kind: ServiceAccount
  name: dbt
  namespace: dn-dbt
roleRef: 
  kind: Role
  name: dbt-discover
  apiGroup: rbac.authorization.k8s.io
