apiVersion: batch/v1
kind: Job
metadata:
  name: dbt-run
  namespace: dn-dbt
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: dbt
      restartPolicy: Never
      initContainers:
      - name: init
        image: alpine:3.18
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /workspace/dbt-project/models
            cp /scripts/run-dbt.sh /workspace/run-dbt.sh
            chmod +x /workspace/run-dbt.sh
            cp /dbt-project-src/dbt_project.yml /workspace/dbt-project/dbt_project.yml
            cp /dbt-project-src/profiles.yml /workspace/dbt-project/profiles.yml
            cp /dbt-project-src/str_test.sql /workspace/dbt-project/models/str_test.sql
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: dbt-project-src
          mountPath: /dbt-project-src
        - name: workspace
          mountPath: /workspace
      containers:
      - name: dbt
        image: python:3.9-slim
        command: ["/bin/sh", "/workspace/run-dbt.sh"]
        volumeMounts:
        - name: workspace
          mountPath: /workspace
      volumes:
      - name: scripts
        configMap:
          name: dbt-scripts
          defaultMode: 0755
      - name: dbt-project-src
        configMap:
          name: dbt-project
      - name: workspace
        emptyDir: {}